/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    ConfigForm: typeof import('./src/components/common/ConfigForm.vue')['default']
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    CustomMultiSelect: typeof import('./src/components/common/CustomMultiSelect.vue')['default']
    CustomSelect: typeof import('./src/components/common/CustomSelect.vue')['default']
    FileDropzone: typeof import('./src/components/common/FileDropzone.vue')['default']
    ImageDropzone: typeof import('./src/components/common/ImageDropzone.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    MonacoEditor: typeof import('./src/components/common/MonacoEditor.vue')['default']
    NotificationContainer: typeof import('./src/components/common/NotificationContainer.vue')['default']
    PageContainer: typeof import('./src/components/layout/PageContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleSwitch: typeof import('./src/components/common/ToggleSwitch.vue')['default']
  }
}
