from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional, Union, Type

from core.utils.tool_utils import BaseTool


@dataclass
class ToolSet:
    """A set of tools"""
    tools: list[BaseTool] = field(default_factory=list)

    def __contains__(self, item):
        for tool in self.tools:
            if tool.name == item:
                return True
        return False

    def add(self, *tools: Union[BaseTool, Type[BaseTool]]):
        for tool in tools:
            if isinstance(tool, type):
                tool_inst = tool()
            elif isinstance(tool, BaseTool):
                tool_inst = tool
            else:
                continue
            for i, t in enumerate(self.tools):
                if t.name == tool.name:
                    self.tools.pop(i)
            self.tools.append(tool_inst)

    def remove(self, tool_name: str):
        for i, t in enumerate(self.tools):
            if t.name == tool_name:
                self.tools.pop(i)

    def get(self, tool_name: str):
        for tool in self.tools:
            if tool.name == tool_name:
                return tool

    def to_list(self):
        tool_list = []
        for tool in self.tools:
            tool_list.append({
                "type": "function",
                "function": tool.get_schema()
            })
        return tool_list


@dataclass
class ToolResult:
    """tool result, support text, image and file result"""

    text: str

    attachments: list[Attachment] = field(default_factory=list)

    result_str: str = field(init=False)

    def assemble_result(self):
        attachments_text = ""
        if self.attachments:
            attachments_text = "\n".join(att.name for att in self.attachments)

        res_text = (
            self.text if self.text else "",
            "\n--- Attachments ---\n" if attachments_text else "",
            attachments_text,
        )
        self.result_str = "".join(res_text)
        return self.result_str


@dataclass
class Attachment:
    """An attachment generated by plugins"""

    """Filename with extension, e.g. my_video.mp4"""
    name: str

    """Attachment content"""
    attachment: str

    """MIME Type, e.g. image/png, video/mp4, application/pdf"""
    mime: Optional[str] = None
